mysql:
  host: 172.17.0.3
  port: 3306
  db: schedule
  username: root
  password: 123456
  parameters: charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true

gorm:
 # 是否开启调试模式
  debug: true
  # 数据库类型(目前支持的数据库类型：mysql/sqlite3/postgres)
  db_type: mysql
  # 设置连接可以重用的最长时间(单位：秒)
  max_lifetime: 7200
  # 设置数据库的最大打开连接数
  max_open_conns: 150
  # 设置空闲连接池中的最大连接数
  max_idle_conns: 50
  # 数据库表名前缀
  table_prefix: ""
  # 是否启用自动映射数据库表结构
  enable_auto_migrate: true

mongo:
  host: 172.17.0.5
  port: 27017
  db: schedule
  username: ""
  password: ""
  authSource: "admin"

mail:
  server: smtp.exmail.qq.com
  subject: "定时任务监控结果"
  receiver:
    - 1731692911@qq.com
    - leisunsun98@gmail.com
  stmp:
    user: sunlei@aizinger.com
    password: uu4DzbcvcBaMddde
    port: 465
